volumes:
  # Reusable persistent volumes.
  database-kss-data:

services:
  databse-kss:
    container_name: "databse-kss-mssql"
    build: "./mssql"
    env_file:
      - .env
    ports:
      - "1451:1433"
    volumes:
      - database-kss-data:/var/opt/mssql
